Repository aio-libs/aiomonitor, pull requests merged in 2023-12, with the labels that each got.

#389 Improve Python 3.12 compatibility
  .github/workflows/ci-cd.yml
  changes/389.fix.md
  requirements-dev.txt
  setup.cfg
  tests/test_monitor.py
Labels: deps-update, dependencies, maintenance

#390 Fix license classifier
  setup.cfg
Labels: bug, maintenance

#391 ci: Replace black, flake8, and isort with ruff
  .flake8
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  aiomonitor/task.py
  aiomonitor/webui/utils.py
  changes/391.fix.rst
  docs/conf.py
  pyproject.toml
  requirements-dev.txt
Labels: maintenance

#393 doc: Update the docs to match with the latest
  aiomonitor/monitor.py
  aiomonitor/termui/commands.py
  docs/api.rst
  docs/conf.py
  docs/index.rst
  docs/reference/monitor.rst
  docs/reference/termui.rst
  docs/reference/webui.rst
  docs/tty.gif
  docs/tutorial.rst
  docs/webui-demo1.gif
  examples/web_srv_custom_monitor.py
  requirements-doc.txt
Labels: enhancement

#385 feature: Add a demo example for PyCon APAC 2023 talk
  aiomonitor/monitor.py
  changes/385.feature.rst
  examples/demo.py
Labels: enhancement

#394 docs: Update tutorial a little bit more
  docs/tutorial.rst
Labels: enhancement
